### ISSUE TITLE
Get Transcript from OCAS - Scheduled Worker - Unit Tested

### ISSUE THREAD

**Issue by moonrockfamily** [EduShareOntario/studentTranscriptOCASIntegration#2]
This component periodically:
- [x] contacts the OCAS web service and gets any outstanding 'transcripts'
- [ ] creates a chain of tasks/jobs to process each ◦It does not implement the actual task/job logic but merely establishes the work process/chain and lets the specific 'worker' do the actual work. (time remaining: 4 hours)
- [ ] sends an acknowledgment to OCAS indicating that we have successfully retrieved the transcripts. (time remaining: 2 hours)
- [ ] resiliency configuration and verification (time remaining: 2 hours)
- [ ] test windows service configuration and verification ( 1 hour)

**Comment by kristapm** [comment]
In progress
