### ISSUE TITLE
SVATREQ  - processes for checks & update of the indicators;  move the records not working

### ISSUE THREAD

**Issue by shosein** [EduShareOntario/studentTranscriptOCASIntegration#21]
Nicole and Charlotte have done some testing of SVATREQ. The process seems to do the initial processing ok where it stops the requests that did not meet validation and completes those that are ok to go and updates SHARQTC correctly. However when they go to manually process those entries that were stopped, we run into the following types of issues:

1.	When manually processing a transcript in the “Incomplete NOW” queue, it does move the record over to the main complete queue but does not remove it from the “Incomplete NOW” queue. 
2.	Generating a transcript does not appear to update the indicators and populate SHARQTC with the actual transcript request
3.	Any new holds added do not get picked up in the manual processing. 
4.	Generate a refusal also does not appear to update the indicators 
5.	For those records that did generate a SHARQTC record, the complete indicator did not update. (not sure if this comes later in the new process)

From what we see, it would seem that the form itself is probably ok but the processes to do the checks and update of the indicators and move the records between the queues is not happening. 

Charlotte/Nicole can show you if you would like.

**Comment by mdwmax** [comment]
I believe these issues have been resolved. Please advise

**Comment by shosein** [comment]
RESOLVED:)
