### ISSUE TITLE
View Queue link....broken 

### ISSUE THREAD

**Issue by shosein** [EduShareOntario/studentTranscriptOCASIntegration#22]
![view queue](https://cloud.githubusercontent.com/assets/15947632/11473503/d21b0404-9740-11e5-97c9-6e1c83eb2979.png)

Should we be able to use this link or is there another URL we should use?

**Comment by mdwmax** [comment]
We have an issue with the server not starting up correctly. Not sure why - we are looking into it. No eta

**Comment by mdwmax** [comment]
Susan - were you able to ever successfully hit that url

**Comment by shosein** [comment]
Yes...since Todd sent it to me... Same one Charlotte an Nicole used successfully.

Susan

On Dec 1, 2015, at 10:40 AM, mdwmax <notifications@github.com<mailto:notifications@github.com>> wrote:


Susan - were you able to ever successfully hit that url

**Comment by moonrockfamily** [comment]
The test url has changed to http://apps.georgiantest.com/transcript/review
