### ISSUE TITLE
SVATREQ and related forms and processes - Jan 18

### ISSUE THREAD

**Issue by shosein** [EduShareOntario/studentTranscriptOCASIntegration#28]
We discussed To Do’s with Mike about SVATREQ in our meeting on Friday these were the updates we received:

Update for SVATREQ:

Fixed – the issue of requests being in multiple queues (incomplete NOW, and competed) at the same time.

Outstanding:

1)	Investigating the forms SHIEPTD/SHIPTD for possible audit trail (see what date/institutions transcript was sent to), as current SVATREQ 130/147 status does not indicate when transcript has been sent back to OCAS, only that transcript is ready to be sent
2)	SVPTREQ – was receiving error when running job process - identified error : is still working  on getting this job to run properly. Transcript process will not be able to run in SVATREQ until this is complete.  Mike did confirm that manually running a job in SVPTREQ will still be part of the process once converted to XML (same as EDI process).
3)	Mentioned to Mike that the refusal process will need to be looked at and tested – as it is currently not working in live with EDI

**Comment by mdwmax** [comment]
I believe this is resolved as well. Can you confirm ?
