### ISSUE TITLE
Add Outbound transcripts to the transcript collection

### ISSUE THREAD

**Issue by moonrockfamily** [EduShareOntario/studentTranscriptOCASIntegration#29]
- [x] After producing an outbound transcript, add it to the collection of transcripts.
- [ ] Exclude outbound transcripts from pending review filter.

**Comment by moonrockfamily** [comment]
ddp.call("createTranscript", [{title:"Outbound Transcript", description:"generateTranscript created me", outbound: true, pescCollegeTranscriptXML: transcriptDetails.PESCXml}], function(err,transcriptId) {

Note: the second argument of the ddp.call is an array, but may vary depending on the ddpClient library in use.  See https://github.com/sonyarouje/DDPClient.NET/blob/master/Net.DDP.Client/DDPClient.cs  line 34... `Call(string methodName, params object[] args)`

**Comment by mdwmax** [comment]
This is working, was initially an issue with the connection protocol when we went live so the first set of transcripts we sent to OCAS aren't in the queue. The transcripts are also currently being saved on the file system and in the database. These are configurable parameters, I thought it best to turn these on during the initial go live stage.

**Comment by shosein** [comment]
Yes, to confirm, it is working from our end.  thanks!
