### ISSUE TITLE
Transcript Request Validator - Unit Tested

### ISSUE THREAD

**Issue by moonrockfamily** [EduShareOntario/studentTranscriptOCASIntegration#4]
- [ ] schema validate (1 hour)
- [ ] critical info check ( 2 hour)
- [ ] update job status (1 hour)
- [ ] resiliency configuration and verification (2 hours)
- [ ] test windows service configuration and verification ( 1 hour)

**Comment by kristapm** [comment]
Question: What if it fails?  Is the user notified?  How?  Q for Susan or Cathy...
