### ISSUE TITLE
Refactor sql code in processTranscriptsToSendWorker process

### ISSUE THREAD

**Issue by mdwmax** [EduShareOntario/studentTranscriptOCASIntegration#40]
The code is currently passing sql into the database to update the banner tables.
(svrtreq, xml_agency,svrtnte).

I want to move that code into georgian.svptreq_pkg package.

**Comment by shosein** [comment]
Will this result in down time or additional testing or ??

**Comment by mdwmax** [comment]
Down time - yes, it would be very brief, 5 minutes at most.
Testing would be brief as well, 30 minutes to confirm that  the records are being written properly.
